### ISSUE TITLE
Start child process in cloud code

### ISSUE THREAD

**Issue by noyessie** [parse-community/parse-cli#74]
It is possible to start child process on cloud code ?

If yes, how ?

**Comment by flovilmart** [comment]
see node documentation: https://nodejs.org/api/child_process.html

**Comment by noyessie** [comment]
always done. but i continoeusly got

```
/app/node_modules/parse-server/lib/ParseServer.js:218
           throw err;
           ^
 
 Error: write EPIPE
     at WriteWrap.afterWrite [as oncomplete] (net.js:832:14)
 Program node app.js exited with code 7

```
I dont know why `ParseServer.js` trow this error.

**Comment by flovilmart** [comment]
This seems completely unrelated.

What does trigger this error? (I just tried this:

```

Parse.Cloud.define('run', () => {
  const cp = require('child_process');
  const res = cp.execSync('ls');
  return res.toString();
});
```

and it properly gets the list of files in the current directory.

**Comment by noyessie** [comment]
I think the same. when i run the same command, it work fine. but the real command i need to execute do not work. this is source code:

```js
let promise = new Parse.Promise();
  let destination = TEMP_DIR + uuidv1()+".png";
  let video_source_stream = new stream.PassThrough();

  video_source_stream.push(video_buffer);
  var command = "avconv -i pipe:0 -loglevel quiet -r 25 -ss 1 -frames:v 1 -f image2 "+destination;
  try{
    var process_aconv = exec(command , (err , stdout , stderr)=>{
      console.log("output stdout" , stdout);
      console.log("output err" , err);
      console.log("output stderr" , stderr);
    });
    video_source_stream.pipe(process_aconv.stdin);
  }catch(err){
    console.log("incomprehensive error with avconv");
  }
```

The cash not work and the error stop server.

**Comment by flovilmart** [comment]
So, it is related but it isn't:

It is related because there is an [uncaughtException handler](https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly) in the transpiled code at your line (in the source [here](https://github.com/parse-community/parse-server/blob/master/src/ParseServer.js#L170))

The thing is, your program is yielding the exception, and because it's a stream based process, the exception occurs *asynchronously* ie: the try/catch is no use there.

I'll be closing as it's related to your code and there's nothing we can do to fix it internally.

One last question, what is the full stacktrace?

**Comment by noyessie** [comment]
I already give it.
```
/app/node_modules/parse-server/lib/ParseServer.js:218
           throw err;
           ^
 
 Error: write EPIPE
     at WriteWrap.afterWrite [as oncomplete] (net.js:832:14)
 Program node app.js exited with code 7
```

**Comment by noyessie** [comment]
@flovilmart thank for you help.

I decid to write file to disk and use it in command. so no pipe and all work fine. I will find go solution later because i think IO action is not good for performance issues.

**Comment by flovilmart** [comment]
Next time, consider using stackoverflow for implementation details questions. The github issues are for reporting bugs within the different projects.
